name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
      - name: Send report to Telegram
        if: always()
        run: |
          STATUS="Success"
          if [ ${{ steps.test.outcome }} != "success" ]; then
            STATUS="Failed"
          fi

          curl -X POST "https://api.telegram.org/bot7824475005:AAHMni_EljMyh3L8qKqXdafbetJD9gUxnkY/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{"chat_id": "473468570", "text": "Playwright Tests: *'${STATUS}'*%0ARepository: '${{ github.repository }}'%0ABranch: '${{ github.ref_name }}'%0AJob URL: '${{ github.run_url }}'", "parse_mode": "Markdown"}'
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
